[package]
name = "kafkacanc"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
zip = "2.4.2"
walkdir = "2.5.0"
chrono = "0.4.40"
eframe = "0.31.1"
rfd = "0.15.3"
image = "0.25.5"

[profile.release]
strip = true
