[package]
name = "kafkaBackup"
version = "0.1.2"
edition = "2024"
build = "build.rs"

[dependencies]
chrono = "0.4.40"
dirs = "6.0.0"
eframe = "0.31.1"
dotenv = "0.15.0"
image = "0.25.6"
rfd = "0.15.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
walkdir = "2.5.0"
zip = "2.5.0"

[build-dependencies]
embed-resource = "3.0.2"

[profile.release]
strip = true
