[package]
name = "kafkacanc"
version = "0.1.0"
edition = "2024"

[dependencies]
zip = "2.4.2"
walkdir = "2.5.0"
chrono = "0.4.40"
eframe = "0.31.1"
rfd = "0.15.3"  # For native file/folder pickers
image = "0.25.5"
